CREATE TABLE SOCIETA (
  IDSoc INT NOT NULL PRIMARY KEY,
  TotAzioni INT NOT NULL,
  Stato VARCHAR(50) NOT NULL
);

CREATE TABLE SOCI (
  Nome VARCHAR(50) NOT NULL PRIMARY KEY,
  StatoResidenza VARCHAR(50) NOT NULL
);

CREATE TABLE QUOTE (
  IDSoc INT NOT NULL,
  Socio VARCHAR(50) NOT NULL,
  NumAzioni INT NOT NULL,
  PRIMARY KEY (IDSoc, Socio),
  FOREIGN KEY (IDSoc) REFERENCES SOCIETA(IDSoc),
  FOREIGN KEY (Socio) REFERENCES SOCI(Nome)
);

INSERT INTO SOCIETA VALUES (1, 1000, 'Topolinia');
INSERT INTO SOCIETA VALUES (2, 100, 'Italia');
INSERT INTO SOCIETA VALUES (3, 1000, 'USA');
INSERT INTO SOCIETA VALUES (4, 500, 'Francia');
INSERT INTO SOCIETA VALUES (5, 200, 'Topolinia');

INSERT INTO SOCI VALUES ('Paperino', 'Paperopoli');
INSERT INTO SOCI VALUES ('Topolino', 'Topolinia');
INSERT INTO SOCI VALUES ('Rossi', 'Italia');
INSERT INTO SOCI VALUES ('Bianchi', 'Italia');
INSERT INTO SOCI VALUES ('Smith', 'USA');
INSERT INTO SOCI VALUES ('Doe', 'USA');
INSERT INTO SOCI VALUES ('Dupont', 'Francia');

INSERT INTO QUOTE VALUES (1, 'Paperino', 450);
INSERT INTO QUOTE VALUES (1, 'Topolino', 550);
INSERT INTO QUOTE VALUES (2, 'Rossi', 100);
INSERT INTO QUOTE VALUES (3, 'Smith', 600);
INSERT INTO QUOTE VALUES (3, 'Doe', 100);
INSERT INTO QUOTE VALUES (3, 'Rossi', 300);
INSERT INTO QUOTE VALUES (4, 'Rossi', 300);
INSERT INTO QUOTE VALUES (4, 'Bianchi', 200);
INSERT INTO QUOTE VALUES (5, 'Paperino', 20);
INSERT INTO QUOTE VALUES (5, 'Topolino', 180);
